// lib/projects.js — single source of truth for all project data

export const projects = [
  {
    slug: 'keenkeeper',
    num: '01',
    name: 'KeenKeeper',
    tagline: 'Friendship Management App',
    emoji: '🌿',
    image: '/screenshots/keenkeeper.png',
    images: [
      '/screenshots/keenkeeper.png',
      '/screenshots/keenkeeper-2.png',
      '/screenshots/keenkeeper-3.png',
      '/screenshots/keenkeeper-4.png',
    ],
    demo: 'https://a-07-keen-keeper.vercel.app/',
    github: 'https://github.com/MdHadiuzzaman0/A_07_KeenKeeper',
    tech: ['React.js', 'React Router v7', 'Context API', 'Recharts', 'Tailwind CSS', 'DaisyUI', 'React Toastify'],
    description: 'A specialized relationship management application designed to help users stay meaningfully connected with the people who matter most. Track friendships, log interactions and visualize activity stats — all in a clean, responsive interface powered by React Router v7 and Context API.',
    challenges: [
      'Implementing global state across deeply nested components without prop drilling — solved with Context API (MotherProvider pattern).',
      'Using React Router v7 loader functions to pre-fetch JSON data before component render, ensuring no loading flicker on navigation.',
      'Building a real-time interaction timeline with multi-mode filtering (by type, date, name) while keeping state consistent across re-renders.',
      'Rendering Recharts pie chart dynamically with a graceful fallback for the "No Activity" empty state.',
    ],
    improvements: [
      'Add a backend (Node.js + MongoDB) to persist friend data and interaction history across sessions.',
      'Implement user authentication so multiple users can manage their own friend lists.',
      'Add push notification reminders when a friend is "overdue" for contact.',
      'Introduce a mobile app version using React Native.',
    ],
  },
  {
    slug: 'digitools',
    num: '02',
    name: 'DigiTools',
    tagline: 'Digital Product Marketplace',
    emoji: '🛒',
    image: '/screenshots/digitools.png',
    images: [
      '/screenshots/digitools.png',
      '/screenshots/digitools-2.png',
      '/screenshots/digitools-3.png',
    ],
    demo: 'https://digi-tools-platform-ten.vercel.app/',
    github: 'https://github.com/MdHadiuzzaman0/DigiTools_Platform',
    tech: ['React 19', 'use() Hook', 'Suspense', 'Tailwind CSS', 'DaisyUI', 'React Toastify', 'Lucide React'],
    description: 'A fully functional digital product marketplace where users can browse premium tools, add them to a cart, view dynamic pricing plans and proceed through checkout — all in a clean, responsive single-page application built with React 19 modern patterns.',
    challenges: [
      "Managing shared cart state (coin, selected) across Navbar, Products, SingleCard and Cart without a state library — solved via state lifting in App.jsx.",
      "Using React 19's experimental use() hook for Promise-based data fetching — required careful Suspense boundary placement to avoid UI blocking.",
      'Preventing duplicate cart entries with real-time visual feedback — button state changes from "Buy Now" to "✓ Added" immediately.',
      'Keeping three JSON data sources (products, steps, pricing) in sync with Suspense without blocking the full page render.',
    ],
    improvements: [
      'Integrate a real payment gateway (Stripe or SSLCommerz) for actual checkout flow.',
      'Add a backend with user accounts, order history and wishlist functionality.',
      'Implement product search, category filtering and sort options.',
      'Add product reviews and star ratings system.',
    ],
  },
  {
    slug: 'english-janala',
    num: '03',
    name: 'English Janala',
    tagline: 'Interactive Vocabulary Learning Platform',
    emoji: '📚',
    image: '/screenshots/english-janala.png',
    images: [
      '/screenshots/english-janala.png',
      '/screenshots/english-janala-2.png',
      '/screenshots/english-janala-3.png',
      '/screenshots/english-janala-4.png',
    ],
    demo: 'https://english-janala-iota.vercel.app/',
    github: 'https://github.com/MdHadiuzzaman0/English_Janala',
    tech: ['HTML5', 'Tailwind CSS', 'DaisyUI', 'Vanilla JavaScript ES6+', 'Web Speech API', 'REST API'],
    description: 'An interactive English vocabulary learning tool with real-time search, lesson-based browsing and built-in audio pronunciation using the Web Speech API. Dynamic content is loaded from an external API with modal-based detailed word views including meaning, synonyms and example sentences.',
    challenges: [
      'Implementing the Web Speech API for pronunciation — handling browser compatibility and ensuring graceful fallback when the API is unavailable.',
      'Building a real-time search that filters from a large vocabulary dataset without any performance lag using vanilla JS.',
      'Managing multiple async API calls (lesson list + word list) with proper loading states without any external library.',
      'Creating an accessible modal system without React — pure DOM manipulation with proper focus trapping.',
    ],
    improvements: [
      'Rebuild with React for better component architecture and state management.',
      'Add spaced repetition algorithm (SRS) for smarter vocabulary review scheduling.',
      'Implement user progress tracking with localStorage or a MongoDB backend.',
      'Add quiz mode and gamification elements to improve long-term engagement.',
    ],
  },
  {
    slug: 'github-issue-tracker',
    num: '04',
    name: 'GitHub Issue Tracker',
    tagline: 'React Bug Tracking System',
    emoji: '🐛',
    image: '/screenshots/github/LoginPage.png',
    images: [
      '/screenshots/github/LoginPage.png',
      '/screenshots/github/HomePage.png',
      '/screenshots/github/Allbutton.png',
      '/screenshots/github/Modal.png',
      '/screenshots/github/Search.png',
    ],
    demo: 'https://a-05-git-hub-issue-tracker.vercel.app/',
    github: 'https://github.com/MdHadiuzzaman0/A-05_GitHub_Issue_Tracker',
    tech: ['React.js', 'Tailwind CSS', 'Dynamic Filtering', 'Local Authentication', 'Component Architecture'],
    description: 'A React-based bug tracking system with login authentication (demo: admin/admin123), dynamic filtering by status and label, and a clean dashboard UI. Built with component-driven architecture and local state management for real-time filter updates without page reload.',
    challenges: [
      'Implementing a multi-criteria filter system (status + label simultaneously) with correct state synchronization across re-renders.',
      'Building a simple but functional local authentication flow that feels secure without a backend.',
      'Keeping the component tree clean and modular while passing filter state through multiple levels without Context.',
      'Designing a dashboard layout that clearly communicates issue priority and status at a glance.',
    ],
    improvements: [
      'Connect to the real GitHub REST API to pull actual repository issues dynamically.',
      'Add create, edit and close issue functionality with optimistic UI updates.',
      'Implement role-based access control (admin vs viewer permissions).',
      'Add analytics dashboard showing issue resolution trends over time with charts.',
    ],
  },
]

export function getProject(slug) {
  return projects.find(p => p.slug === slug) || null
}